service: serverless-iopipe-demo

plugins:
  - serverless-plugin-iopipe

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    IOPIPE_TOKEN: ${env:IOPIPE_TOKEN}

custom:
  iopipeExclude: helloWithTrace

functions:
  hello:
    handler: withHello.handler
    events:
      - http:
          path: hello
          method: get
          cors: true
  helloWithError:
    handler: withError.handler
    events:
      - http:
          path: hello/error
          method: get
          cors: true
  helloWithTrace:
    handler: withTrace.handler
    events:
      - http:
          path: hello/trace
          method: get
          cors: true
